#!/bin/sh

for f in `ls posts/*.m*` 
do
	./compile $f
done

for f in `ls columns/**/*.m*` 
do
	./compile $f
done

for f in `ls digests/*.m*` 
do
	./compile $f
done


for f in `ls references/**/*.m*` 
do
	./compile $f
done

