#!/bin/sh

./compile dashboard.markdown
./compile favorite.markdown
./compile free-programming-books.md
./compile slogan.md
./compile whoami.md
./compile references.md
./compile interlinks.md
./compile columns.md
./compile payme.md

for f in `ls columns/**/*.m*`
do
	./compile $f
done

for f in `ls references/**/*.m*`
do
	./compile $f
done

amm build.sc
# sbt run
