#!/bin/sh

./compile dashboard.markdown
./compile favorite.markdown
./compile free-programming-books.md
./compile slogan.md
./compile whoami.md
./compile references.md
./compile interlinks.md

sbt run
